### ISSUE TITLE
How does Response decorator work?

### ISSUE THREAD

**Issue by cevatkerim** [jfrconley/valory#1]
Can you provide an example?

**Comment by jfrconley** [comment]
`@Response` is intended to quickly document additional return types.

For example:
```ts
@Response(203, "Explosion", {potato: true})
@Post("/other/{thing}/")
public test(@Path() thing: string, @Body() input: ParentType): string {
	this.logger.info("A thing has happen");
	return "stuff";
}
```
This would add a 203 response to the documentation with the status code 203, description "Explosion", and example {"potato": true}.

NOTE: There is currently a bug that prevents the example from being included. This has been fixed in 6fe127235dbbd791970525df9813ea572fc5398d
